# Generated by Django 5.1.5 on 2025-02-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_post', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
